project                  = "falkon-staging-b6f2"
project_prefix           = "falkon"
region                   = "us-east4"
environment              = "staging"
user_management_base_url = "https://api-staging.falkon.dsgov.demo.nuvalence.io/um"
