project                  = "falkon-dev-b6f2"
project_prefix           = "falkon"
region                   = "us-east4"
environment              = "dev"
user_management_base_url = "https://api-dev.falkon.dsgov.demo.nuvalence.io/um"
