name: File Change Notification

on:
  push:
    paths:
      - 'terraform/shared_locals.tf'
      - 'terraform/shared_main.tf'
      - 'terraform/shared_variables.tf'
      - 'terraform/dev/dev.auto.tfvars'
      - 'terraform/demo/demo.auto.tfvars'
    branches:    
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Notify on File Change
      run: python .github/scripts/notify_on_file_change.py
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.DSGOV_SLACK_WEBHOOK }}
